runtime: nodejs20
env: standard
instance_class: F1

env_variables:
  PORT: "8080"
  NODE_ENV: "production"
  FRONTEND_URL: "http://localhost:5173"

  # Mongo
  DATABASE_URI: "mongodb+srv://globogreen:gzVJW0bFWzYG4uP4@globogreen-cluster01.lhlbh.mongodb.net/Association"

  # Admin seed
  ADMIN_EMAIL_ID: "globogreenmobile@gmail.com"
  ADMIN_PASSWORD: "Dhar@1254"

  GOOGLE_EMAIL_ID_1: "globogreenmobile@gmail.com"
  GOOGLE_EMAIL_ID_2: "snandhadeveloper592000@gmail.com"

  ENABLE_LOGIN_OTP: "false"

  # Email / Resend / Nodemailer
  RESEND_API: "re_D3GdcHn1_LxvtmrPmA3vj8D5AoorKP21N"
  FROM_EMAIL: "noreply@globogreen.in"
  NODEMAILER_EMAIL: "globogreenmobile@gmail.com"
  NODEMAILER_PASSWORD: "ucuilakgvpryzcdj"

  # JWT
  JWT_ACCESS_SECRET: "JDKFJ3498FJASD09F8ASD7F6ASDJDKFJ3498FJASD09F8ASD7F6"
  JWT_REFRESH_SECRET: "JDKFJ3498FJASD09F8ASD7F6ASDJDKFJ3498FJASD09F8ASD7F6"

  # Cloudinary
  CLOUDINARY_CLOUD_NAME: "dg6c0g4gi"
  CLOUDINARY_API_KEY: "694635395288588"
  CLOUDINARY_API_SECRET: "geEEuXbhDF5Wy0T8RuOTM8IpXh8"

  # Google OAuth
  GOOGLE_CLIENT_ID: "1042792160295-bph5fru21702m2tcsqd3q6hvr7a1mlih.apps.googleusercontent.com"
